import = ["/home/greed/.config/alacritty/tokyonight/tokyonight-night.toml"]

[cursor.style]
shape = "Underline"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "GeistMono Nerd Font"



[window.padding]
x = 2
y = 1
