#setups
format = "$python$battery$directory "
right_format = "$git_branch$git_status $cmd_duration"

[character]
success_symbol = "[ 󰀘  ](bg:#89b4fa fg:#1e1e2e)"
error_symbol = "[ ](#f38ba8)"
vicmd_symbol = "[  ](#f9e2af)"

[directory]
format = "[ 󰀘  ](bg:#89b4fa fg:#1e1e2e)[ $path ](bg:#1e1e2e fg:#cdd6f4)"


[cmd_duration]
min_time = 1
# duration & style 
format = "[[ 󰔚 ](bg:#161821 fg:#eba0ac bold)$duration ](bg:#161821 fg:#BBC3DF)"
disabled = false
style = "bg:none fg:#161821"

#battery
[battery]
full_symbol = " 󰂄"
charging_symbol = " "
discharging_symbol = " 󰂅 "

[[battery.display]]
threshold = 30

[git_branch]
format = "[[  ](bg:#0f0 fg:#A2DD9D bold)$branch ](bg:#0f0 fg:#86AAEC)"

[git_status]
# $all status$ahead_behind
format = "[$all_status$ahead_behind ](bg:#161821 fg:#b4befe)"
style = "bg:none fg:#161821"
conflicted = "="
ahead =	" ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = " "
untracked = " ?${count}"
modified = " !${count}"
staged = " +${count}"
deleted = " ${count}"
stashed = " "
renamed = " »${count}"

[python]
symbol = " "
format = '[]($style)[(\($virtualenv\))](bg:#161821 fg:#BBC3DF)[ ]($style)'
style = "bg:none fg:#161821"
