format = " $battery$directory "
right_format = " $java$lua$python$git_branch$git_status $cmd_duration "

# [directory]
# format = "[ 󰀘  ](bg:#0f0 fg:#fff) [ $path ](bg:#0f0 fg:#cdd6f4)"
# truncation_length = 1
# fish_style_pwd_dir_length = 1


[directory]
format = "[ 󰀘  ](bg:#6d8dad fg:#1e1e2e)[ $path ](bg:#484b4c fg:#cdd6f4)"
truncation_length = 1
fish_style_pwd_dir_length = 1


[cmd_duration]
min_time = 1
# duration & style 
format = "[[ 󰔚 ](bg:#32302f fg:#ff75a0 bold)$duration ](bg:#32302f fg:#BBC3DF)"
disabled = false
style = "bg:none fg:#161821"

[battery]
full_symbol = "󰂄"
charging_symbol = ""
discharging_symbol = "󰂅 "

[[battery.display]]
threshold = 30

[git_branch]
format = "[[  ](bg:#32302f fg:#A2DD9D bold)$branch](bg:#32302f fg:#86AAEC)"

[git_status]
# $all status$ahead_behind
format = "[$all_status$ahead_behind ](bg:#32302f fg:#b4befe)"
style = "bg:none fg:#161821"
conflicted = "="
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = " "
untracked = " ?${count}"
modified = " !${count}"
staged = " +${count}"
deleted = " 󰅖${count}"
stashed = " 󰏖"
renamed = " »${count}"

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )](bold yellow)'
# format = '[(\($virtualenv\)) ](bg:#161821 fg:#BBC3DF)'
# style = "bg:none fg:#fab387"

[lua]
symbol = ""
format = ' [$symbol $version](bold blue) '

[java]
symbol = ""
# format = ' [$symbol $version_format](bold blue) '
format = ' [${symbol} (${version})](bold red)'
